### PR TITLE
Changing amplitude example to output values in dB

### PR DESCRIPTION
**Pull request by OmarAli3**

### CODE REVIEW

**Comment by per1234** [comment]
Fixes https://github.com/arduino-libraries/ArduinoSound/issues/16

**Comment by MisterAwesome23** [comment]
I feel it can be improved minutely.

No need to use abs(), two reasons, technically sound can be negative decibels also, the amplitudeAnalyzer.read() should ideally return a non negative value so no need of abs()

**Comment by OmarAli3** [comment]
Hi @MisterAwesome23, thanks for your comment.
* Regarding first reason, taking abs() inside log() will not prevent negative values so decibels still can be negative.
* Regarding second reason, I am not very sure but in practice amplitude can be negative so took into consideration.

**Review by aentinger — APPROVED** [review]
LGTM :+1: Thank you @OmarAli3 🚀

**Pull request merged**
